# Generated by Django 2.2 on 2019-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qte',
            field=models.IntegerField(default='0'),
        ),
    ]
